In [1]:
import torch 
import torch.nn.functional as F

In [2]:
# 임의의 문장 임베딩 데이터 
# 3개의 단어에 각 단어는 4개의 차원의 숫자로 표현
x = torch.randn(3, 4)
x

tensor([[ 0.0215, -0.2385, -0.5685, -1.0463],
        [-1.5165, -0.1256, -1.2051,  0.0699],
        [ 0.8559,  0.6818, -0.9264, -1.6540]])

In [3]:
# Query, Key, Value의 임의의 가중치 행렬로 생성 ( 원래는 학습이 되는 가중치 행렬 부분 )
w_q = torch.randn(4, 4)
w_k = torch.randn(4, 4)
w_v = torch.randn(4, 4)

In [4]:
# x의 데이터와 각각의 가중치 행렬을 곱하여 q, k, v를 생성 
q = torch.matmul(x, w_q)
k = torch.matmul(x, w_k)
v = torch.matmul(x, w_v)

In [5]:
# Attention Score를 생성  -> Query와 Key의 내적
attention_score = torch.matmul( q, k.T )

In [6]:
# Attention_score는 고차원일수록 발산를 하기 때문에 Key 차원의 수의 루트의 씌워서 나눠준다. 
d_k = k.size(1)

In [7]:
# 스케일링과 스프크맥스를 통해서 확률로 변환 (모든 행의 합이 1)
attention_weight = F.softmax( attention_score / (d_k ** 0.5), dim=1 )
attention_weight

tensor([[0.5365, 0.1610, 0.3025],
        [0.1012, 0.2467, 0.6520],
        [0.8821, 0.0462, 0.0717]])

In [8]:
output = torch.matmul(attention_weight, v)
output

tensor([[ 0.9279,  0.0175, -1.0509,  0.5948],
        [ 0.7702,  0.1478, -1.5691,  0.7966],
        [ 0.8303, -0.1764, -0.7704,  0.4732]])